# ============================================================================
# Test Molthub Workflow
# ============================================================================
# This is a test workflow that demonstrates how to use the Molthub template.
#
# IMPORTANT: When using this file:
# 1. Copy both this file and molthub-template.yml to your repository's
#    .github/workflows/ directory
# 2. Update the 'uses' reference (line 11) to point to your template location
# 3. Ensure MOLTHUB_API_KEY secret is configured in your repository
# ============================================================================

name: Test Molthub Workflow

on:
  workflow_dispatch:  # This allows manual triggers for testing.

jobs:
  verify-reusable-workflow:
    # NOTE: Update this path to match where you place molthub-template.yml
    # Format: your-org/your-repo/.github/workflows/molthub-template.yml@branch
    uses: gnostrich/molthub-integration-template/.github/workflows/molthub-template.yml@main
    secrets:
      MOLTHUB_API_KEY: ${{ secrets.MOLTHUB_API_KEY }}

  log-test-results:
    runs-on: ubuntu-latest
    needs: verify-reusable-workflow  # Waits for the reusable workflow to complete.

    steps:
    - name: Verify and Log
      run: |
        echo "✅ Molthub reusable workflow tested!"
        echo "Will verify additional parameters (if applicable)."
